// Generated by view binder compiler. Do not edit!
package com.example.myjewellary.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.myjewellary.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityRegisterBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final ImageView registerApplogo;

  @NonNull
  public final Button registerBtn;

  @NonNull
  public final EditText registerPasswordInput;

  @NonNull
  public final EditText registerPhoneNumberInput;

  @NonNull
  public final EditText registerUsernameInput;

  private ActivityRegisterBinding(@NonNull RelativeLayout rootView,
      @NonNull ImageView registerApplogo, @NonNull Button registerBtn,
      @NonNull EditText registerPasswordInput, @NonNull EditText registerPhoneNumberInput,
      @NonNull EditText registerUsernameInput) {
    this.rootView = rootView;
    this.registerApplogo = registerApplogo;
    this.registerBtn = registerBtn;
    this.registerPasswordInput = registerPasswordInput;
    this.registerPhoneNumberInput = registerPhoneNumberInput;
    this.registerUsernameInput = registerUsernameInput;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityRegisterBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityRegisterBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_register, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityRegisterBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.register_applogo;
      ImageView registerApplogo = ViewBindings.findChildViewById(rootView, id);
      if (registerApplogo == null) {
        break missingId;
      }

      id = R.id.register_btn;
      Button registerBtn = ViewBindings.findChildViewById(rootView, id);
      if (registerBtn == null) {
        break missingId;
      }

      id = R.id.register_password_input;
      EditText registerPasswordInput = ViewBindings.findChildViewById(rootView, id);
      if (registerPasswordInput == null) {
        break missingId;
      }

      id = R.id.register_phone_number_input;
      EditText registerPhoneNumberInput = ViewBindings.findChildViewById(rootView, id);
      if (registerPhoneNumberInput == null) {
        break missingId;
      }

      id = R.id.register_username_input;
      EditText registerUsernameInput = ViewBindings.findChildViewById(rootView, id);
      if (registerUsernameInput == null) {
        break missingId;
      }

      return new ActivityRegisterBinding((RelativeLayout) rootView, registerApplogo, registerBtn,
          registerPasswordInput, registerPhoneNumberInput, registerUsernameInput);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
