// Generated by view binder compiler. Do not edit!
package com.example.myjewellary.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.myjewellary.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityMainBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final ImageView appLogo;

  @NonNull
  public final TextView appSlogan;

  @NonNull
  public final Button mainJoinLoginBtn;

  @NonNull
  public final Button mainJoinNowBtn;

  private ActivityMainBinding(@NonNull RelativeLayout rootView, @NonNull ImageView appLogo,
      @NonNull TextView appSlogan, @NonNull Button mainJoinLoginBtn,
      @NonNull Button mainJoinNowBtn) {
    this.rootView = rootView;
    this.appLogo = appLogo;
    this.appSlogan = appSlogan;
    this.mainJoinLoginBtn = mainJoinLoginBtn;
    this.mainJoinNowBtn = mainJoinNowBtn;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_main, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMainBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.app_logo;
      ImageView appLogo = ViewBindings.findChildViewById(rootView, id);
      if (appLogo == null) {
        break missingId;
      }

      id = R.id.app_slogan;
      TextView appSlogan = ViewBindings.findChildViewById(rootView, id);
      if (appSlogan == null) {
        break missingId;
      }

      id = R.id.main_join_login_btn;
      Button mainJoinLoginBtn = ViewBindings.findChildViewById(rootView, id);
      if (mainJoinLoginBtn == null) {
        break missingId;
      }

      id = R.id.main_join_now_btn;
      Button mainJoinNowBtn = ViewBindings.findChildViewById(rootView, id);
      if (mainJoinNowBtn == null) {
        break missingId;
      }

      return new ActivityMainBinding((RelativeLayout) rootView, appLogo, appSlogan,
          mainJoinLoginBtn, mainJoinNowBtn);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
